org: leomontoya
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::087688905490:role/LabRole

functions:
  scrape_table_IGP:
    handler: scrap_table_IGP.lambda_handler  # Asegúrarse de que el nombre del archivo y la función coincidan
    package:
      include:
        - ./**  # Incluir todo el contenido del directorio
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrappingIGP
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
